#  Introducción a Numpy, Pandas y matplotlib para el análisis de datos

## Numpy

Numpy es una librería de Python que nos permite trabajar con vectores y matrices de forma eficiente. Es una de las librerías más importantes para el análisis de datos en Python. Pero primerto, ¿qué es un vector y qué es una matriz?

*Vector:* en `numpy` un vector es una colección de una dimensión. Se puede pensar como valores en una columna de una tabla. Por ejemplo, la edad de los alumnos de una clase.

*Matriz:* en `numpy` una matriz es una colección de dos dimensiones. Se puede pensar como una tabla. Por ejemplo, la edad y la altura de los alumnos de una clase.

*Arreglo:* a su vez, un arreglo es una colección de *p* dimensiones. Por ejemplo, la edad, la altura y el peso de los alumnos de una clase es una matriz de 3 dimensiones. Los arreglos es una forma general de referirse a vectores y matrices en cualquier dimensión. 

A diferencia de las listas, los arreglos de `numpy` son homogéneos, es decir, todos los elementos deben ser del mismo tipo. Por ejemplo, todos los elementos de un arreglo pueden ser enteros o flotantes, pero no una mezcla de ambos.

In [7]:
# Crear un vector con numpy
import numpy as np

vector = np.array([1, 2, 3])
print(vector)

[1 2 3]


Recordaremos que si teníamos una lista `x = [1, 2, 3]` y multiplicábamos la lista por 2, obteníamos una lista con los elementos repetidos: `x * 2 = [1, 2, 3, 1, 2, 3]`. En cambio, si tenemos un arreglo `y = np.array([1, 2, 3])` y lo multiplicamos por 2, obtenemos un arreglo con los elementos multiplicados por 2: `y * 2 = np.array([2, 4, 6])`.

In [8]:
vector  = np.array([1, 2, 3])
vector  * 2

array([2, 4, 6])

Podemos convertir una lista en un arreglo con la función `np.array()`.

In [9]:
x = [1, 2, 3]
np.array(x)

array([1, 2, 3])

In [10]:
print(f'x * 2 = {x * 2}')

x * 2 = [1, 2, 3, 1, 2, 3]


In [11]:
 y = np.array(x)
print(f'y * 2 = {y * 2}')

y * 2 = [2 4 6]
